//
//  StoreManager.swift
//  JointStoreProject
//
//  Created by Kislov Vadim on 13.05.2022.
//

import Foundation

class StoreManager {
     static let shared = StoreManager()

     let products = [
        Product(name: "Помидоры розовые",
                description: """
                        Помидоры имеют превосходные вкусовые качества и аромат.
                        Мякоть у плодов данного сорта отличается особенной
                        нежностью и сладковатым вкусом
                    """,
                price: 120),
        Product(name: "Огурцы",
                description: """
                        Огурцы часто используются для приготовления салатов,
                        супов, закусок, смузи, а также прекрасно подходят для зимних
                        заготовок благодаря своему небольшому размеру.
                    """,
                price: 90),
        Product(name: "Перец красный",
                description: """
                        Сочный овощ ярко-красного цвета с мясистой, хрустящей мякотью.
                        Отличается сладким вкусом и свежим ароматом.
                    """,
                price: 200),
        Product(name: "Картофель",
                description: """
                        Картофель отличается ровными, слегка продолговатыми клубнями
                        и тонкой кожурой. Молодой картофель подходит для различных
                        кулинарных экспериментов.
                    """,
                price: 60),
        Product(name: "Редис",
                description: """
                        Редис – сочный, хрустящий корнеплод с пикантным вкусом.
                        Редис благоприятно влияет на здоровье человека.
                    """,
                price: 140),
        Product(name: "Кабачки",
                description: """
                        Этот универсальный продукт широко используется в традиционном,
                        вегетарианском, детском и диетическом питании.
                    """,
                price: 200),
        Product(name: "Баклажаны",
                description: """
                        Баклажан имеет отличительный синий цвет,
                        а сам плод имеет вытянутую овальную форму
                    """,
                price: 210),
        Product(name: "Морковь",
                description: """
                        Морковь отличается ярким сладким вкусом и приятным свежим ароматом.
                    """,
                price: 60),
        Product(name: "Капуста",
                description: """
                        Овощ — кладезь витаминов С, А, В1 и В2, Р, К,
                        а также клетчатки и микроэлементов.
                    """,
                price: 120),
        Product(name: "Свекла",
                description: """
                        Свекла – корнеплод, обладающий сочной, плотной структурой,
                        ярким цветом и сладким вкусом.
                    """,
                price: 130),
        Product(name: "Брокколи",
                description: """
                        Брокколи – очень полезный и диетический овощ.
                        Наиболее он полезен, в сыром и вареном видах.
                    """,
                price: 400),
        Product(name: "Грибы Шампиньоны",
                description: """
                        Этот популярный сорт грибов можно купить в любое время года.
                        Шампиньоны имеют плотную ножку и округлую шляпку.
                    """,
                price: 500),
        Product(name: "Имбирь",
                description: """
                        Продукт является одной из самых распространенных пряностей
                        в мировой кулинарии, используется для приготовления настоев, чаев.
                    """,
                price: 700),
        Product(name: "Свекла",
                description: """
                        Свекла – корнеплод, обладающий сочной, плотной структурой,
                        ярким цветом и сладким вкусом.
                    """,
                price: 120)
     ]

     private init() {}
    
    /// Поиск товара из доступных по полному/частичному названию
    func searchProducts(by search: String) -> [Product] {
        let trimmed = search.trimmingCharacters(in: .whitespacesAndNewlines)
        
        return products.filter { $0.name.contains(trimmed) }
    }
    
    func getTestOrders() -> [Order] {
        [
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.12.2022",
                  totalPrice: Int.random(in: 1000..<50000),
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price:90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.01.2011",
                  totalPrice: 22200,
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "12.12.2022",
                  totalPrice: 33300,
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.12.2022",
                  totalPrice: Int.random(in: 1000..<50000),
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price:90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.01.2011",
                  totalPrice: 22200,
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "12.12.2022",
                  totalPrice: 33300,
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.12.2022",
                  totalPrice: Int.random(in: 1000..<50000),
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price:90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.01.2011",
                  totalPrice: 22200,
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "12.12.2022",
                  totalPrice: 33300,
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.12.2022",
                  totalPrice: Int.random(in: 1000..<50000),
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price:90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.01.2011",
                  totalPrice: 22200,
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "12.12.2022",
                  totalPrice: 33300,
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.12.2022",
                  totalPrice: Int.random(in: 1000..<50000),
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price:90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.01.2011",
                  totalPrice: 22200,
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "12.12.2022",
                  totalPrice: 33300,
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.12.2022",
                  totalPrice: Int.random(in: 1000..<50000),
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price:90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.01.2011",
                  totalPrice: 22200,
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "12.12.2022",
                  totalPrice: 33300,
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.12.2022",
                  totalPrice: Int.random(in: 1000..<50000),
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price:90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.01.2011",
                  totalPrice: 22200,
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "12.12.2022",
                  totalPrice: 33300,
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.12.2022",
                  totalPrice: Int.random(in: 1000..<50000),
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price:90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "08.01.2011",
                  totalPrice: 22200,
                  userIndex: 0),
            Order(items:
                    [ProductItem(product: Product(name: "Помидоры розовые", description: "", price: 120), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Огурцы", description: "", price: 90), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Перец красный", description: "", price: 200), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Картофель", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Батат", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Дайкон", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Сельдерей", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Яблоки", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Апельсины", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Грибы маринованые", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0),
                     ProductItem(product: Product(name: "Колбаса копченая", description: "", price: 60), count: Int.random(in: 1..<50), userIndex: 0)],
                  number: Int.random(in: 100000..<999999),
                  date: "12.12.2022",
                  totalPrice: 33300,
                  userIndex: 0),
        ]
    }
}
